### ISSUE TITLE
How should I process the ADNI dataset if the images only have the '.nii' suffix? If I run the code as is, it will raise an error because '.npy' files do not exist.

### ISSUE THREAD

**Issue by aaaaaannie** [ys-zong/MEDFAIR#12]
![d7f434aa312109e972d1a7fba48727c](https://github.com/user-attachments/assets/6beb547c-e76f-4ab8-a082-fd81d99230cb)

**Comment by ys-zong** [comment]
You can use some existing tools to directly convert .nii to .npy, e.g., https://nipy.org/nibabel/gettingstarted.html

**Comment by ys-zong** [comment]
Closing for now due to inactivity. Feel free to reopen if the issue persists.
