### ISSUE TITLE
Baseline results on Chexpert

### ISSUE THREAD

**Issue by miladmasroor** [ys-zong/MEDFAIR#13]
I ran the baseline method on Chexpert using the default options (ERM with ResNet18) and I'm getting results that are much better than reported in the paper.  For example, for the sex attribute, I'm getting Overall AUC of 0.87, min AUC of 0.86 and gap of 0.02.  The paper shows Overall AUC of 0.88, but a gap of 0.10.  Could there be a default option that is set to help the baseline method to be less biased?

**Comment by ys-zong** [comment]
In Table A9 of the paper, the reported gap of AUC (ERM, CheXpert, sex attribute) is 0.02%, not 0.10.
![image](https://github.com/user-attachments/assets/e91be9ac-4706-4bcd-8981-657282e582eb)

**Comment by miladmasroor** [comment]
I apologize for the mistake. You are correct; the reported gap of AUC (ERM, CheXpert, sex attribute) is indeed 0.02%, not 0.10%. Thank you for pointing that out.
