### ISSUE TITLE
Assistance Needed for Adjusting Age Group Splitting in HAM10000 Dataset

### ISSUE THREAD

**Issue by miladmasroor** [ys-zong/MEDFAIR#14]
I am currently working with the HAM10000 dataset and noticed a discrepancy between the example provided in the HAM10000-example.ipynb file and the published paper. Specifically, the notebook uses 5 different age groups for splitting subjects, while the paper reports results based on 4 different age groups.

I would greatly appreciate your guidance on how to modify the code to split the subjects into 4 age groups instead of 5. Could you please provide the appropriate age range definitions for the 4-group split as used in the paper?

Thank you in advance for your support.

# split subjects to different age groups
demo_data['Age_multi'] = demo_data['age'].values.astype('int')
demo_data['Age_multi'] = np.where(demo_data['Age_multi'].between(-1,19), 0, demo_data['Age_multi'])
demo_data['Age_multi'] = np.where(demo_data['Age_multi'].between(20,39), 1, demo_data['Age_multi'])
demo_data['Age_multi'] = np.where(demo_data['Age_multi'].between(40,59), 2, demo_data['Age_multi'])
demo_data['Age_multi'] = np.where(demo_data['Age_multi'].between(60,79), 3, demo_data['Age_multi'])
demo_data['Age_multi'] = np.where(demo_data['Age_multi']>=80, 4, demo_data['Age_multi'])

**Comment by ys-zong** [comment]
Hi, I recall I discarded 0-20 age group because it has too few samples. You can just remove this group and use the other four groups.
![image](https://github.com/user-attachments/assets/d17f11d0-3e9b-463c-868b-93724b32ab49)

**Comment by miladmasroor** [comment]
Thank you so much for your help and guidance. I appreciate the clarification about discarding the 0-20 age group. I’ll proceed with the other four groups as suggested.
