### ISSUE TITLE
For one dataset do i have to train 11 algorithms manually?

### ISSUE THREAD

**Issue by aaaaaannie** [ys-zong/MEDFAIR#7]

**Comment by ys-zong** [comment]
Hi. You can train whichever algorithm of interest. Or you can use the script [here](https://github.com/ys-zong/MEDFAIR/blob/main/sweep/train-sweep/sweep_batch.py) to launch all training at one time.

**Comment by aaaaaannie** [comment]
> Hi. You can train whichever algorithm of interest. Or you can use the script [here](https://github.com/ys-zong/MEDFAIR/blob/main/sweep/train-sweep/sweep_batch.py) to launch all training at one time.

Have some problem matching OCT dataset, the size of dataset did not have the same channel with code.

**Comment by ys-zong** [comment]
Can you describe the problem in detail and paste the error log if there's any?
