### ISSUE TITLE
Optimizer choice

### ISSUE THREAD

**Issue by Carco-git** [ys-zong/MEDFAIR#8]
Hi, 

I have read your ICLR paper and found you mentioned that "SGD optimizer is used for all methods and we
apply early stopping if the validation worst-case AUC does not improve for 5 epochs.". However, I can only find the Adam Optimizer in your code implementation. Which optimizer should I use to repeat your experiments?

Thanks!

**Comment by ys-zong** [comment]
Hi, thanks for your interest. For the paper, I used SGD as the optimizer, but later I found that Adam gives similar performance but converges faster especially for smaller datasets. So I changed the code to Adam optimizer in this [commit](https://github.com/ys-zong/MEDFAIR/commit/70ee823449dede7e0719b3adf1d744565f617c2f). If you want to reproduce the results, you can use SGD. If you want to have a faster convergence and potentially better performance, you can use Adam.

**Comment by Carco-git** [comment]
Thank you!
