### ISSUE TITLE
Covid-CT-MD missing preprocessing dicom to numpy?

### ISSUE THREAD

**Issue by SteffGroefsema** [ys-zong/MEDFAIR#9]
First of all, thank you for your elaborate work on the MEDFAIR dataset.
However, I think the preprocessing step how to convert the dicom files of the patients to .npy files is missing. Can you share how you build that part of the dataset?

**Comment by ys-zong** [comment]
Hi, thanks for your interest. I somehow lost the original data preprocessing code for this part, but I think I used [pydicom](https://github.com/pydicom/pydicom) for the conversion. It should be relatively easy if you follow their example to extract the data values.

**Comment by SteffGroefsema** [comment]
Thank you for your response.
